"""Updates the foreign key reference from bet to user (as organizer).

Revision ID: 2d0280b65047
Revises: 7e15c6b3d73b
Create Date: 2016-08-27 20:25:45.525819

"""

# revision identifiers, used by Alembic.
revision = '2d0280b65047'
down_revision = '7e15c6b3d73b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('organizer_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('bet_organizer_fkey', 'bet', type_='foreignkey')
    op.create_foreign_key(None, 'bet', 'user', ['organizer_id'], ['id'])
    op.drop_column('bet', 'organizer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('organizer', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bet', type_='foreignkey')
    op.create_foreign_key('bet_organizer_fkey', 'bet', 'user', ['organizer'], ['id'])
    op.drop_column('bet', 'organizer_id')
    ### end Alembic commands ###
