"""Adds a unique constraint to name and url_name on bets.

Revision ID: 7e15c6b3d73b
Revises: 8b9f5b081137
Create Date: 2016-08-27 18:15:32.180825

"""

# revision identifiers, used by Alembic.
revision = '7e15c6b3d73b'
down_revision = '8b9f5b081137'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bet', ['url_name'])
    op.create_unique_constraint(None, 'bet', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bet', type_='unique')
    op.drop_constraint(None, 'bet', type_='unique')
    ### end Alembic commands ###
